Default: &defaults
#  host: "*4" # any IPv4 host
  port: 3000
#  approot: "http://localhost:3000"
  copyright: Copyright (c) Krzysztof SkrzÄ™tnicki 2012
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://personallibrary.herokuapp.com"
  <<: *defaults
